---
- name: Upgrade existing packages.
  yum:
    update_cache: yes
    name: '*'
    state: latest
  register: sys_updated

- name: Restart Server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: sys_updated.changed == True

- name: Waiting for server restart completion
  local_action: wait_for host={{ ansible_host }} state=started delay=10 timeout=100
  become: false

- name: Install Satellite packages.
  yum:
    name: satellite
    state: latest
